all:
  children:
    gitlab:
      hosts:
        gitlab-01:
          ansible_host: gitlab-01
          ansible_user: laborant
    gitlab_runner:
      hosts:
        runner-01:
          ansible_host: runner-01
          ansible_user: laborant